services:
  nextjs:
    image: balisunt/private:ecommerce-fe-latest-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app_network

networks:
  app_network:
    name: app_network
